/**
 * Starting hands, strongest first. Generated by tools/gen-handrank.test.ts —
 * do not edit by hand.
 *
 * `equity` is the raw chance of beating one random hand all-in to the river,
 * measured over 30,000 deals. The ordering adds a small playability bonus for
 * suited and connected hands, because all-in equity alone undervalues hands
 * that win by making flushes and straights over several streets.
 *
 * `percentile` (below) is what the bots actually use: "this hand is in the
 * top N% of all starting hands".
 */

export interface RankedHand {
  name: string;
  /** Class index in the 13x13 grid used by engine/range.ts. */
  index: number;
  equity: number;
  rank: number;
}

export const RANKED_HANDS: RankedHand[] = [
  { name: 'AA', index: 0, equity: 0.8504, rank: 0 },
  { name: 'KK', index: 14, equity: 0.8253, rank: 1 },
  { name: 'QQ', index: 28, equity: 0.8022, rank: 2 },
  { name: 'JJ', index: 42, equity: 0.7739, rank: 3 },
  { name: 'TT', index: 56, equity: 0.7450, rank: 4 },
  { name: '99', index: 70, equity: 0.7220, rank: 5 },
  { name: 'AKs', index: 1, equity: 0.6753, rank: 6 },
  { name: 'AQs', index: 2, equity: 0.6647, rank: 7 },
  { name: '88', index: 84, equity: 0.6945, rank: 8 },
  { name: 'AJs', index: 3, equity: 0.6480, rank: 9 },
  { name: 'KQs', index: 15, equity: 0.6343, rank: 10 },
  { name: '77', index: 98, equity: 0.6682, rank: 11 },
  { name: 'AKo', index: 13, equity: 0.6520, rank: 12 },
  { name: 'ATs', index: 4, equity: 0.6448, rank: 13 },
  { name: 'A9s', index: 5, equity: 0.6340, rank: 14 },
  { name: 'KJs', index: 16, equity: 0.6244, rank: 15 },
  { name: 'AQo', index: 26, equity: 0.6435, rank: 16 },
  { name: 'KTs', index: 17, equity: 0.6224, rank: 17 },
  { name: 'AJo', index: 39, equity: 0.6377, rank: 18 },
  { name: 'QJs', index: 29, equity: 0.5991, rank: 19 },
  { name: 'KQo', index: 27, equity: 0.6161, rank: 20 },
  { name: 'A8s', index: 6, equity: 0.6201, rank: 21 },
  { name: '66', index: 112, equity: 0.6291, rank: 22 },
  { name: 'ATo', index: 52, equity: 0.6265, rank: 23 },
  { name: 'QTs', index: 30, equity: 0.5909, rank: 24 },
  { name: 'K9s', index: 18, equity: 0.5988, rank: 25 },
  { name: 'A7s', index: 7, equity: 0.6087, rank: 26 },
  { name: 'KJo', index: 40, equity: 0.6077, rank: 27 },
  { name: 'JTs', index: 43, equity: 0.5782, rank: 28 },
  { name: 'A5s', index: 9, equity: 0.5978, rank: 29 },
  { name: 'A6s', index: 8, equity: 0.5977, rank: 30 },
  { name: 'K8s', index: 19, equity: 0.5837, rank: 31 },
  { name: 'Q9s', index: 31, equity: 0.5776, rank: 32 },
  { name: 'A9o', index: 65, equity: 0.6016, rank: 33 },
  { name: '55', index: 126, equity: 0.6000, rank: 34 },
  { name: 'A4s', index: 10, equity: 0.5897, rank: 35 },
  { name: 'QJo', index: 41, equity: 0.5830, rank: 36 },
  { name: 'KTo', index: 53, equity: 0.5938, rank: 37 },
  { name: 'A3s', index: 11, equity: 0.5844, rank: 38 },
  { name: 'A8o', index: 78, equity: 0.5996, rank: 39 },
  { name: 'J9s', index: 44, equity: 0.5538, rank: 40 },
  { name: 'K7s', index: 20, equity: 0.5747, rank: 41 },
  { name: 'A2s', index: 12, equity: 0.5742, rank: 42 },
  { name: 'Q8s', index: 32, equity: 0.5620, rank: 43 },
  { name: 'QTo', index: 54, equity: 0.5745, rank: 44 },
  { name: 'K6s', index: 21, equity: 0.5685, rank: 45 },
  { name: 'A7o', index: 91, equity: 0.5904, rank: 46 },
  { name: 'K9o', index: 66, equity: 0.5777, rank: 47 },
  { name: 'T9s', index: 57, equity: 0.5374, rank: 48 },
  { name: 'K5s', index: 22, equity: 0.5621, rank: 49 },
  { name: 'JTo', index: 55, equity: 0.5527, rank: 50 },
  { name: '44', index: 140, equity: 0.5683, rank: 51 },
  { name: 'A6o', index: 104, equity: 0.5799, rank: 52 },
  { name: 'Q7s', index: 33, equity: 0.5418, rank: 53 },
  { name: 'J8s', index: 45, equity: 0.5374, rank: 54 },
  { name: 'A5o', index: 117, equity: 0.5746, rank: 55 },
  { name: 'K8o', index: 79, equity: 0.5591, rank: 56 },
  { name: 'T8s', index: 58, equity: 0.5265, rank: 57 },
  { name: 'K4s', index: 23, equity: 0.5475, rank: 58 },
  { name: 'A4o', index: 130, equity: 0.5679, rank: 59 },
  { name: 'Q9o', index: 67, equity: 0.5488, rank: 60 },
  { name: 'K3s', index: 24, equity: 0.5399, rank: 61 },
  { name: 'A3o', index: 143, equity: 0.5607, rank: 62 },
  { name: 'Q6s', index: 34, equity: 0.5356, rank: 63 },
  { name: '98s', index: 71, equity: 0.5063, rank: 64 },
  { name: 'J7s', index: 46, equity: 0.5205, rank: 65 },
  { name: 'J9o', index: 68, equity: 0.5330, rank: 66 },
  { name: 'K7o', index: 92, equity: 0.5522, rank: 67 },
  { name: 'K2s', index: 25, equity: 0.5291, rank: 68 },
  { name: 'Q5s', index: 35, equity: 0.5265, rank: 69 },
  { name: '33', index: 154, equity: 0.5364, rank: 70 },
  { name: 'A2o', index: 156, equity: 0.5451, rank: 71 },
  { name: 'K6o', index: 105, equity: 0.5441, rank: 72 },
  { name: 'Q8o', index: 80, equity: 0.5316, rank: 73 },
  { name: 'T9o', index: 69, equity: 0.5135, rank: 74 },
  { name: 'T7s', index: 59, equity: 0.5028, rank: 75 },
  { name: 'J6s', index: 47, equity: 0.5061, rank: 76 },
  { name: 'Q4s', index: 36, equity: 0.5178, rank: 77 },
  { name: '97s', index: 72, equity: 0.4903, rank: 78 },
  { name: 'J8o', index: 81, equity: 0.5163, rank: 79 },
  { name: 'Q3s', index: 37, equity: 0.5095, rank: 80 },
  { name: 'K5o', index: 118, equity: 0.5312, rank: 81 },
  { name: 'Q7o', index: 93, equity: 0.5159, rank: 82 },
  { name: '87s', index: 85, equity: 0.4751, rank: 83 },
  { name: 'T6s', index: 60, equity: 0.4909, rank: 84 },
  { name: 'J5s', index: 48, equity: 0.5018, rank: 85 },
  { name: 'Q2s', index: 38, equity: 0.5012, rank: 86 },
  { name: 'K4o', index: 131, equity: 0.5232, rank: 87 },
  { name: '22', index: 168, equity: 0.5049, rank: 88 },
  { name: 'T8o', index: 82, equity: 0.4956, rank: 89 },
  { name: 'J4s', index: 49, equity: 0.4936, rank: 90 },
  { name: 'K3o', index: 144, equity: 0.5145, rank: 91 },
  { name: '98o', index: 83, equity: 0.4862, rank: 92 },
  { name: 'Q6o', index: 106, equity: 0.5119, rank: 93 },
  { name: '96s', index: 73, equity: 0.4736, rank: 94 },
  { name: 'J7o', index: 94, equity: 0.4955, rank: 95 },
  { name: 'K2o', index: 157, equity: 0.5062, rank: 96 },
  { name: '86s', index: 86, equity: 0.4628, rank: 97 },
  { name: '76s', index: 99, equity: 0.4540, rank: 98 },
  { name: 'T5s', index: 61, equity: 0.4672, rank: 99 },
  { name: 'J3s', index: 50, equity: 0.4787, rank: 100 },
  { name: 'Q5o', index: 119, equity: 0.5001, rank: 101 },
  { name: 'J6o', index: 107, equity: 0.4824, rank: 102 },
  { name: '95s', index: 74, equity: 0.4586, rank: 103 },
  { name: '97o', index: 96, equity: 0.4708, rank: 104 },
  { name: 'T7o', index: 95, equity: 0.4751, rank: 105 },
  { name: 'J2s', index: 51, equity: 0.4690, rank: 106 },
  { name: 'T4s', index: 62, equity: 0.4686, rank: 107 },
  { name: 'Q4o', index: 132, equity: 0.4866, rank: 108 },
  { name: 'Q3o', index: 145, equity: 0.4828, rank: 109 },
  { name: '85s', index: 87, equity: 0.4446, rank: 110 },
  { name: '65s', index: 113, equity: 0.4313, rank: 111 },
  { name: 'T3s', index: 63, equity: 0.4585, rank: 112 },
  { name: '94s', index: 75, equity: 0.4458, rank: 113 },
  { name: '75s', index: 100, equity: 0.4368, rank: 114 },
  { name: '87o', index: 97, equity: 0.4489, rank: 115 },
  { name: 'J5o', index: 120, equity: 0.4755, rank: 116 },
  { name: 'Q2o', index: 158, equity: 0.4743, rank: 117 },
  { name: 'T2s', index: 64, equity: 0.4505, rank: 118 },
  { name: 'T6o', index: 108, equity: 0.4572, rank: 119 },
  { name: '54s', index: 127, equity: 0.4175, rank: 120 },
  { name: '84s', index: 88, equity: 0.4326, rank: 121 },
  { name: 'J4o', index: 133, equity: 0.4646, rank: 122 },
  { name: '96o', index: 109, equity: 0.4434, rank: 123 },
  { name: '93s', index: 76, equity: 0.4363, rank: 124 },
  { name: 'J3o', index: 146, equity: 0.4578, rank: 125 },
  { name: '74s', index: 101, equity: 0.4185, rank: 126 },
  { name: '76o', index: 111, equity: 0.4281, rank: 127 },
  { name: 'T5o', index: 121, equity: 0.4416, rank: 128 },
  { name: '86o', index: 110, equity: 0.4315, rank: 129 },
  { name: '64s', index: 114, equity: 0.4081, rank: 130 },
  { name: '92s', index: 77, equity: 0.4231, rank: 131 },
  { name: '53s', index: 128, equity: 0.4001, rank: 132 },
  { name: '83s', index: 89, equity: 0.4074, rank: 133 },
  { name: 'T4o', index: 134, equity: 0.4386, rank: 134 },
  { name: 'J2o', index: 159, equity: 0.4386, rank: 135 },
  { name: '95o', index: 122, equity: 0.4264, rank: 136 },
  { name: '43s', index: 141, equity: 0.3866, rank: 137 },
  { name: '63s', index: 115, equity: 0.3975, rank: 138 },
  { name: '73s', index: 102, equity: 0.3998, rank: 139 },
  { name: '85o', index: 123, equity: 0.4147, rank: 140 },
  { name: '65o', index: 125, equity: 0.4026, rank: 141 },
  { name: '75o', index: 124, equity: 0.4088, rank: 142 },
  { name: 'T3o', index: 147, equity: 0.4290, rank: 143 },
  { name: '82s', index: 90, equity: 0.4025, rank: 144 },
  { name: '94o', index: 135, equity: 0.4092, rank: 145 },
  { name: '72s', index: 103, equity: 0.3845, rank: 146 },
  { name: '52s', index: 129, equity: 0.3792, rank: 147 },
  { name: 'T2o', index: 160, equity: 0.4160, rank: 148 },
  { name: '42s', index: 142, equity: 0.3699, rank: 149 },
  { name: '32s', index: 155, equity: 0.3604, rank: 150 },
  { name: '62s', index: 116, equity: 0.3755, rank: 151 },
  { name: '54o', index: 139, equity: 0.3793, rank: 152 },
  { name: '74o', index: 137, equity: 0.3868, rank: 153 },
  { name: '84o', index: 136, equity: 0.3902, rank: 154 },
  { name: '64o', index: 138, equity: 0.3800, rank: 155 },
  { name: '93o', index: 148, equity: 0.3978, rank: 156 },
  { name: '92o', index: 161, equity: 0.3955, rank: 157 },
  { name: '83o', index: 149, equity: 0.3758, rank: 158 },
  { name: '53o', index: 152, equity: 0.3629, rank: 159 },
  { name: '43o', index: 153, equity: 0.3498, rank: 160 },
  { name: '73o', index: 150, equity: 0.3646, rank: 161 },
  { name: '63o', index: 151, equity: 0.3602, rank: 162 },
  { name: '82o', index: 162, equity: 0.3700, rank: 163 },
  { name: '72o', index: 163, equity: 0.3448, rank: 164 },
  { name: '42o', index: 166, equity: 0.3344, rank: 165 },
  { name: '52o', index: 165, equity: 0.3393, rank: 166 },
  { name: '62o', index: 164, equity: 0.3415, rank: 167 },
  { name: '32o', index: 167, equity: 0.3187, rank: 168 },
];

/** Combos in each class, before card removal: 6 pairs, 4 suited, 12 offsuit. */
function comboCount(name: string): number {
  if (name.length === 2) return 6;
  return name.endsWith('s') ? 4 : 12;
}

const TOTAL_COMBOS = 1326;

/**
 * Share of all starting hands at least as strong as this one, 0..1.
 * A hand with percentile 0.15 is in the top 15% of hands.
 */
export const HAND_PERCENTILE: Record<string, number> = (() => {
  const out: Record<string, number> = {};
  let seen = 0;
  for (const h of RANKED_HANDS) {
    seen += comboCount(h.name);
    out[h.name] = seen / TOTAL_COMBOS;
  }
  return out;
})();

export const PERCENTILE_BY_INDEX: number[] = (() => {
  const out = new Array(169).fill(1);
  for (const h of RANKED_HANDS) out[h.index] = HAND_PERCENTILE[h.name];
  return out;
})();
