/**
 * Generator, not a test: writes src/bots/handRank.ts.
 *
 * Ranks all 169 starting-hand classes by equity against one random hand,
 * measured by Monte Carlo with a fixed seed, then adds a small playability
 * bonus for suited and connected hands — raw all-in equity undervalues hands
 * that make flushes and straights, which is what actually wins multi-street
 * pots at these stakes.
 *
 * Run with:  npx vitest run tools/gen-handrank.test.ts
 */

import { writeFileSync } from 'node:fs';
import { it } from 'vitest';
import { ALL_CLASSES, classCombos, type HandClass } from '../src/engine/range';
import { evaluate } from '../src/engine/evaluator';
import { makeRng } from '../src/engine/equity';
import { NUM_CARDS, RANKS, type Card } from '../src/engine/cards';

const SIMS = 30_000;

function equityVsRandom(cls: HandClass, seed: number): number {
  const combos = classCombos(cls);
  const rng = makeRng(seed);
  let won = 0;
  let total = 0;

  for (let i = 0; i < SIMS; i++) {
    const [h1, h2] = combos[i % combos.length];
    const used = new Uint8Array(NUM_CARDS);
    used[h1] = 1;
    used[h2] = 1;

    const draw = (): Card => {
      for (;;) {
        const c = Math.floor(rng() * NUM_CARDS);
        if (!used[c]) {
          used[c] = 1;
          return c;
        }
      }
    };

    const o1 = draw();
    const o2 = draw();
    const board = [draw(), draw(), draw(), draw(), draw()];

    const mine = evaluate([h1, h2, ...board]);
    const theirs = evaluate([o1, o2, ...board]);
    if (mine > theirs) won += 2;
    else if (mine === theirs) won += 1;
    total += 2;
  }
  return won / total;
}

function label(cls: HandClass): string {
  const hi = RANKS[cls.high];
  const lo = RANKS[cls.low];
  if (cls.kind === 'pair') return hi + lo;
  return hi + lo + (cls.kind === 'suited' ? 's' : 'o');
}

it('generates the starting-hand ranking', () => {
  const scored = ALL_CLASSES.map((cls, i) => {
    const eq = equityVsRandom(cls, 7000 + i);
    const gap = cls.high - cls.low;

    // Playability on top of raw all-in equity.
    let bonus = 0;
    if (cls.kind === 'suited') bonus += 0.022;
    if (cls.kind !== 'pair') {
      if (gap === 1) bonus += 0.016;
      else if (gap === 2) bonus += 0.009;
      else if (gap === 3) bonus += 0.004;
      else if (gap >= 6) bonus -= 0.012; // Q3o and friends flop nothing useful
    }
    return { cls, name: label(cls), score: eq + bonus, equity: eq };
  });

  scored.sort((a, b) => b.score - a.score);

  const lines = scored.map(
    (s, rank) =>
      `  { name: '${s.name}', index: ${s.cls.index}, ` +
      `equity: ${s.equity.toFixed(4)}, rank: ${rank} },`,
  );

  const file = `/**
 * Starting hands, strongest first. Generated by tools/gen-handrank.test.ts —
 * do not edit by hand.
 *
 * \`equity\` is the raw chance of beating one random hand all-in to the river,
 * measured over ${SIMS.toLocaleString('en-US')} deals. The ordering adds a small playability bonus for
 * suited and connected hands, because all-in equity alone undervalues hands
 * that win by making flushes and straights over several streets.
 *
 * \`percentile\` (below) is what the bots actually use: "this hand is in the
 * top N% of all starting hands".
 */

export interface RankedHand {
  name: string;
  /** Class index in the 13x13 grid used by engine/range.ts. */
  index: number;
  equity: number;
  rank: number;
}

export const RANKED_HANDS: RankedHand[] = [
${lines.join('\n')}
];

/** Combos in each class, before card removal: 6 pairs, 4 suited, 12 offsuit. */
function comboCount(name: string): number {
  if (name.length === 2) return 6;
  return name.endsWith('s') ? 4 : 12;
}

const TOTAL_COMBOS = 1326;

/**
 * Share of all starting hands at least as strong as this one, 0..1.
 * A hand with percentile 0.15 is in the top 15% of hands.
 */
export const HAND_PERCENTILE: Record<string, number> = (() => {
  const out: Record<string, number> = {};
  let seen = 0;
  for (const h of RANKED_HANDS) {
    seen += comboCount(h.name);
    out[h.name] = seen / TOTAL_COMBOS;
  }
  return out;
})();

export const PERCENTILE_BY_INDEX: number[] = (() => {
  const out = new Array(169).fill(1);
  for (const h of RANKED_HANDS) out[h.index] = HAND_PERCENTILE[h.name];
  return out;
})();
`;

  writeFileSync(new URL('../src/bots/handRank.ts', import.meta.url), file);

  const top = scored.slice(0, 14).map((s) => s.name).join(' ');
  const bottom = scored.slice(-6).map((s) => s.name).join(' ');
  console.log(`\n  сильнейшие: ${top}\n  слабейшие:  ${bottom}\n`);
}, 300_000);
